### PR TITLE
Update swapr staking contracts (April)

### PR DESCRIPTION
**Pull request by shuklaayush**
Addresses #392
```
Events In This Transaction
--------------------------
├── Gnosis Safe (0xb364bAb258ad35dd83c7dd4E8AC78676b7aa1e9F)
│   └── SafeMultiSigTransaction
│       ├── to: 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D
│       ├── value: 0
│       ├── data: 0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001e40085386c3ce0679b035a9f8f17f531c076d0b35954000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000249dd373b9000000000000000000000000d090a6b7651d9e51fe4d25c6756623613fdb79500043942ceae98cc7485b48a37fbb1aa5035e1c8b46000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000249dd373b9000000000000000000000000be7dbb01e87f4fad154b8ab36125181f32a96b2c0022f340c2604dc1cdbe26cac5838ea9ebc8862a46000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000249dd373b90000000000000000000000000e84da346a2c439970857981f580d664265ebcf0004aec063bb5322c9d4c1f46572f432aae3b78b87c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000249dd373b9000000000000000000000000d1d9210c74def67ed6d9652552de77b12c62c00b00000000000000000000000000000000000000000000000000000000
│       ├── operation: 1
│       ├── safeTxGas: 0
│       ├── baseGas: 0
│       ├── gasPrice: 0
│       ├── gasToken: 0x0000000000000000000000000000000000000000
│       ├── refundReceiver: 0x0000000000000000000000000000000000000000
│       ├── signatures: 0x00000000000000000000000054cf9df9dcd78e470ab7cb892d7bfbe114c025fc00000000000000000000000000000000000000000000000000000000000000000100000000000000000000000059c68a651a1f49c26145666e9d5647b1472912a900000000000000000000000000000000000000000000000000000000000000000100000000000000000000000069874c84a30a3742cc2b624238cfeea24cf5ef82000000000000000000000000000000000000000000000000000000000000000001
│       └── additionalInfo: 0x000000000000000000000000000000000000000000000000000000000000000200000000000000000000000054cf9df9dcd78e470ab7cb892d7bfbe114c025fc0000000000000000000000000000000000000000000000000000000000000003
│
├── DXswap (0xA66b20912cBEa522278f3056B4aE60D0d3EE271b)
│   └── Transfer
│       ├── from: 0xD9A998f2998Bc4810A0303B603a7d4ad312fdCb2
│       ├── to: 0x85386C3cE0679b035a9F8F17f531C076d0b35954
│       └── value: 340287648197692786070
│
├── IERC20StakingRewardsDistribution (0xD9A998f2998Bc4810A0303B603a7d4ad312fdCb2)
│   └── Withdrawn
│       ├── withdrawer: 0x85386C3cE0679b035a9F8F17f531C076d0b35954
│       └── amount: 340287648197692786070
│
├── DXswap (0xA66b20912cBEa522278f3056B4aE60D0d3EE271b)
│   ├── Approval
│   │   ├── owner: 0x85386C3cE0679b035a9F8F17f531C076d0b35954
│   │   ├── spender: 0xD9A998f2998Bc4810A0303B603a7d4ad312fdCb2
│   │   └── value: 0
│   ├── Approval
│   │   ├── owner: 0x85386C3cE0679b035a9F8F17f531C076d0b35954
│   │   ├── spender: 0xd090a6b7651d9E51FE4D25c6756623613FdB7950
│   │   └── value: 115792089237316195423570985008687907853269984665640564039457584007913129639935
│   └── Transfer
│       ├── from: 0x85386C3cE0679b035a9F8F17f531C076d0b35954
│       ├── to: 0xd090a6b7651d9E51FE4D25c6756623613FdB7950
│       └── value: 340287648197692786070
│
├── IERC20StakingRewardsDistribution (0xd090a6b7651d9E51FE4D25c6756623613FdB7950)
│   └── Staked
│       ├── staker: 0x85386C3cE0679b035a9F8F17f531C076d0b35954
│       └── amount: 340287648197692786070
│
├── DXswap (0x9A17D97Fb5f76F44604270448Ac77D55Ac40C15c)
│   └── Transfer
│       ├── from: 0x28f2a93d9e41C703b5199007c3E22692A2D335eF
│       ├── to: 0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46
│       └── value: 12813168629095
│
├── IERC20StakingRewardsDistribution (0x28f2a93d9e41C703b5199007c3E22692A2D335eF)
│   └── Withdrawn
│       ├── withdrawer: 0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46
│       └── amount: 12813168629095
│
├── DXswap (0x9A17D97Fb5f76F44604270448Ac77D55Ac40C15c)
│   ├── Approval
│   │   ├── owner: 0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46
│   │   ├── spender: 0x28f2a93d9e41C703b5199007c3E22692A2D335eF
│   │   └── value: 0
│   ├── Approval
│   │   ├── owner: 0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46
│   │   ├── spender: 0xbe7Dbb01E87f4faD154B8AB36125181f32A96B2c
│   │   └── value: 115792089237316195423570985008687907853269984665640564039457584007913129639935
│   └── Transfer
│       ├── from: 0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46
│       ├── to: 0xbe7Dbb01E87f4faD154B8AB36125181f32A96B2c
│       └── value: 12818877641727
│
├── IERC20StakingRewardsDistribution (0xbe7Dbb01E87f4faD154B8AB36125181f32A96B2c)
│   └── Staked
│       ├── staker: 0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46
│       └── amount: 12818877641727
│
├── DXswap (0x3C6bd88cdD2AECf466E22d4ED86dB6B8953FDb72)
│   └── Transfer
│       ├── from: 0x56EEa3787EfA7D3a78E3c3D047dd9186aC1Ab801
│       ├── to: 0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46
│       └── value: 2506903465736383154922
│
├── IERC20StakingRewardsDistribution (0x56EEa3787EfA7D3a78E3c3D047dd9186aC1Ab801)
│   └── Withdrawn
│       ├── withdrawer: 0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46
│       └── amount: 2506903465736383154922
│
├── DXswap (0x3C6bd88cdD2AECf466E22d4ED86dB6B8953FDb72)
│   ├── Approval
│   │   ├── owner: 0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46
│   │   ├── spender: 0x56EEa3787EfA7D3a78E3c3D047dd9186aC1Ab801
│   │   └── value: 0
│   ├── Approval
│   │   ├── owner: 0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46
│   │   ├── spender: 0x0E84da346a2c439970857981f580D664265eBCf0
│   │   └── value: 115792089237316195423570985008687907853269984665640564039457584007913129639935
│   └── Transfer
│       ├── from: 0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46
│       ├── to: 0x0E84da346a2c439970857981f580D664265eBCf0
│       └── value: 2506903465736383154922
│
├── IERC20StakingRewardsDistribution (0x0E84da346a2c439970857981f580D664265eBCf0)
│   └── Staked
│       ├── staker: 0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46
│       └── amount: 2506903465736383154922
│
├── DXswap (0x6a060a569e04a41794d6b1308865a13F27D27E53)
│   └── Transfer
│       ├── from: 0x6E8807E0d108269D017A8958aae36634FA75742B
│       ├── to: 0x4AeC063BB5322c9d4c1f46572f432aaE3b78b87c
│       └── value: 1539142438213731085
│
├── IERC20StakingRewardsDistribution (0x6E8807E0d108269D017A8958aae36634FA75742B)
│   └── Withdrawn
│       ├── withdrawer: 0x4AeC063BB5322c9d4c1f46572f432aaE3b78b87c
│       └── amount: 1539142438213731085
│
├── DXswap (0x6a060a569e04a41794d6b1308865a13F27D27E53)
│   ├── Approval
│   │   ├── owner: 0x4AeC063BB5322c9d4c1f46572f432aaE3b78b87c
│   │   ├── spender: 0x6E8807E0d108269D017A8958aae36634FA75742B
│   │   └── value: 0
│   ├── Approval
│   │   ├── owner: 0x4AeC063BB5322c9d4c1f46572f432aaE3b78b87c
│   │   ├── spender: 0xd1D9210C74deF67eD6D9652552dE77B12C62c00b
│   │   └── value: 115792089237316195423570985008687907853269984665640564039457584007913129639935
│   └── Transfer
│       ├── from: 0x4AeC063BB5322c9d4c1f46572f432aaE3b78b87c
│       ├── to: 0xd1D9210C74deF67eD6D9652552dE77B12C62c00b
│       └── value: 1539142438213731085
│
├── IERC20StakingRewardsDistribution (0xd1D9210C74deF67eD6D9652552dE77B12C62c00b)
│   └── Staked
│       ├── staker: 0x4AeC063BB5322c9d4c1f46572f432aaE3b78b87c
│       └── amount: 1539142438213731085
│
└── Gnosis Safe (0xb364bAb258ad35dd83c7dd4E8AC78676b7aa1e9F)
    └── ExecutionSuccess
        ├── txHash: 0x38cc4b04cd1d91b8442d8f32bee51166f69daa3c1256e21339db4528538c99f8
        └── payment: 0
```

```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x106fe6c70>,
│   'safe_address': '0xb364bAb258ad35dd83c7dd4E8AC78676b7aa1e9F',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001e40085386c3ce0679b035a9f8f17f531c076d0b35954000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000249dd373b9000000000000000000000000d090a6b7651d9e51fe4d25c6756623613fdb79500043942ceae98cc7485b48a37fbb1aa5035e1c8b46000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000249dd373b9000000000000000000000000be7dbb01e87f4fad154b8ab36125181f32a96b2c0022f340c2604dc1cdbe26cac5838ea9ebc8862a46000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000249dd373b90000000000000000000000000e84da346a2c439970857981f580d664265ebcf0004aec063bb5322c9d4c1f46572f432aae3b78b87c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000249dd373b9000000000000000000000000d1d9210c74def67ed6d9652552de77b12c62c00b00000000000000000000000000000000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 0,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 2,
│   '_safe_version': '1.3.0',
│   '_chain_id': None
}
```

### CODE REVIEW

**Review by petrovska-petro — COMMENTED** [review]
addresses & calldata lgtm, will be great to have the `staking_contract_update` script converted into the "safe" mode so we can handle this thru the new dev_msig setup

**Comment by jorijnsmit** [comment]
yea any way you can pr a normal style script that we can run onfork @shuklaayush?

**Review by petrovska-petro — APPROVED** [review]
translation to "safe" script mode looks good ✅

**Review by jorijnsmit — APPROVED** [review]
looks great, happy to finally see this in scripted and forkable form :)

confirmed all contracts were deployed by the `DXdaoERC20StakingRewardsDistributionFactory`

**Pull request merged**
