### PR TITLE
chore: add minor patch migration + migrate arbitrum registry

### PR DESCRIPTION
**Pull request by axejintao**
# Summary

Migrate registry to registry v2 on Arbitrum.

## Posting

```
brownie run scripts/badger/registry.py migrate_registry_keys --network abitrum-main-fork
```

Satisfies a partial of #365

### CODE REVIEW

**Comment by petrovska-petro** [comment]
looks good, just missing techops in registry v1, so along the migration revert will jump

**Review by petrovska-petro — DISMISSED** [review]
smooth!

**Comment by axejintao** [comment]
## Polygon Output

Running 'scripts/badger/registry.py::migrate_registry_keys'...
Transaction sent: 0x32744b1c3764fa0c2f810b3e0e9a4996877a7de8e31fc4bdbce147797a4185ee
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 1
  BadgerRegistry.set confirmed   Block: 29040739   Gas used: 115850 (0.58%)

controller was added to the registry at 0xc00e71719d1494886942d6277DAeA20494cf0EeC
Transaction sent: 0x5858bc4468266c8c05415f88407e5641e0d4e8cc983f2da26c3f57dba047deb3
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 2
  BadgerRegistry.set confirmed   Block: 29040740   Gas used: 103823 (0.52%)

guardian was added to the registry at 0xCD3271021e9b35EF862Dd98AFa826b8b5198826d
Transaction sent: 0xd0177b310cf37b26ec6d0f1fda147085a933c3fc1fbb44f0f461c1a8e22778b3
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 3
  BadgerRegistry.set confirmed   Block: 29040741   Gas used: 106796 (0.53%)

keeper was added to the registry at 0x46fA8817624eEA8052093EAb8e3FdF0e2e0443b2
Transaction sent: 0x322e361dfd7e1a64aee423f6a87ed3f791f25b59239d542011f3c71793597b95
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 4
  BadgerRegistry.set confirmed   Block: 29040742   Gas used: 109841 (0.55%)

badgerTree was added to the registry at 0x2C798FaFd37C7DCdcAc2498e19432898Bc51376b
Transaction sent: 0xdbe441429224824c2cc32d2a63be4d0e4f831c2dd30d48db14816e28dbdb58a8
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 5
  BadgerRegistry.set confirmed   Block: 29040743   Gas used: 112790 (0.56%)

BADGER was added to the registry at 0x1FcbE5937B0cc2adf69772D228fA4205aCF4D9b2
Transaction sent: 0x874b609453a0e7bd3a41ad1beb8554e017421896ccb094c054cc9206a696b41d
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 6
  BadgerRegistry.set confirmed   Block: 29040744   Gas used: 115775 (0.58%)

ibBTC was added to the registry at 0x4EaC4c4e9050464067D673102F8E24b2FccEB350
Transaction sent: 0x5f145554baed87082f200a4996cf06dcd6801c174ab784d13bf19ca4a4ab66c1
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 7
  BadgerRegistry.set confirmed   Block: 29040745   Gas used: 104789 (0.52%)

keeperAccessControl was added to the registry at 0x46fA8817624eEA8052093EAb8e3FdF0e2e0443b2
Transaction sent: 0xea8363128c9494c5e9ac066e6bc4610db48be4e0828721f0169a4bf843181e36
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 8
  BadgerRegistry.set confirmed   Block: 29040746   Gas used: 121829 (0.61%)

governance was added to the registry at 0x4977110Ed3CD5eC5598e88c8965951a47dd4e738
Transaction sent: 0x1e064062d87f1bfb1bf762d54cd95bb5657ed39683b614621fa1e900dc9096b1
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 9
  BadgerRegistry.set confirmed   Block: 29040747   Gas used: 124862 (0.62%)

proxyAdminDev was added to the registry at 0xC4fE5Db8D3c0d0f410D6A7496Faa4f1658d2a301
Transaction sent: 0x6c1f45ba12d5325a5c65178540326b40462e5200c2f301f987cfe01918ce69c6
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 10
  BadgerRegistry.set confirmed   Block: 29040748   Gas used: 127919 (0.64%)

proxyAdminTimelock was added to the registry at 0x9208E6c28959c47E58344d5f84d88F07Fca96CFC
Transaction sent: 0x848e3d14e55117b2622b3b89395d23e0375d6994bc8efbd1a51c2d04b849e2b5
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 11
  BadgerRegistry.set confirmed   Block: 29040749   Gas used: 130856 (0.65%)

rewardsLogger was added to the registry at 0xd0EE2A5108b8800D688AbC834445fd03b3b2738e
Transaction sent: 0x8520f0f46ec66a63bfc0ae1c65795cf634f97368f8a1ef7df39d802196f2f0e8
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 12
  BadgerRegistry.set confirmed   Block: 29040750   Gas used: 133781 (0.67%)

techOps was added to the registry at 0xeb7341c89ba46CC7945f75Bd5dD7a04f8FA16327
Transaction sent: 0xe1110213a5f43c2a63462a8e8667f3f7089b2b01770e7c29ad70a9f0d63e6492
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 13
  BadgerRegistry.set confirmed   Block: 29040751   Gas used: 136910 (0.68%)

governanceTimelock was added to the registry at 0x4f7D83623eeB135eB13DBcEA1A87a96945abE9cc
Transaction sent: 0xa5a9d91ba16d3bf980beb84931ddbcd96882fad0f86f4434729dd61b479ae143
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 14
  BadgerRegistry.set confirmed   Block: 29040752   Gas used: 125636 (0.63%)

timelock was added to the registry at 0x4f7D83623eeB135eB13DBcEA1A87a96945abE9cc
Transaction sent: 0xeaf093e9bc5eea2ba3e77d823a1908c5a29ce77288e4ddbaa30e4e3c88fbfd2c
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 0
  Gnosis Safe.approveHash confirmed   Block: 29040739   Gas used: 46184 (0.23%)

Transaction sent: 0x595b5aeb76730ef0775b2cc2123127a7fee720bcbeb3c7b79b59cf91b59761ef
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 67
  Gnosis Safe.approveHash confirmed   Block: 29040740   Gas used: 46184 (0.23%)

Transaction sent: 0x4e2e683f972d150a8b78b1014e8c2f60c8a55e055cdef645325ad0ecb9d6f6d5
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 3
  Gnosis Safe.approveHash confirmed   Block: 29040741   Gas used: 46184 (0.23%)

**Review by jorijnsmit — DISMISSED** [review]
successfully reproduced locally for arb1, poly and mainnet

**Review by petrovska-petro — APPROVED** [review]

**Pull request merged**
