### PR TITLE
small bugs to get arb1 fees wd script to run locally

### PR DESCRIPTION
**Pull request by jorijnsmit**
@jalbrekt85 i had to make some small changes to get script to run locally, thought i might pr it to save time.

still one caveat though; `bDXS.withdrawAll()` gives me a `blockLocked`!

@petrovska-petro thoughts?

### CODE REVIEW

**Comment by petrovska-petro** [comment]
> @jalbrekt85 i had to make some small changes to get script to run locally, thought i might pr it to save time.
> 
> still one caveat though; `bDXS.withdrawAll()` gives me a `blockLocked`!
> 
> @petrovska-petro thoughts?

i think that error in reality steams from the [defend()](https://arbiscan.io/address/0x7fd16fa571ec3118dd1323b75a037ed2fcc2cbf5#code#L1580) from not being approved yet

**Review by petrovska-petro — APPROVED** [review]
LGTM!

as for the block lock will try to resolve as suggested on dmed

**Comment by petrovska-petro** [comment]
after debugging together with @jorijnsmit  seems that the `blockLocked` jumps due to the difference in the forking sim of brownie of which value uses for `block.number`

while [block.number](https://developer.offchainlabs.com/docs/time_in_arbitrum#ethereum-block-numbers-within-arbitrum) is the L1 block, in brownie seems that it is grabbing the `chain.height` instead so reverts

**Comment by jorijnsmit** [comment]
https://github.com/eth-brownie/brownie/issues/1537

**Comment by jalbrekt85** [comment]
nice changes thanks @jorijnsmit

**Pull request merged**
