### PR TITLE
script to deposit 50k badger & equal parts wbtc into our factory pool

### PR DESCRIPTION
**Pull request by jalbrekt85**
**solves #254**, very similar to #34 with cleaned up code. sufficient badger already in trops and required wbtc is siphoned from bibbtc

`brownie run issue/254/deposit_factory`

### CODE REVIEW

**Review by jorijnsmit — CHANGES_REQUESTED** [review]
indeed already done before in #34 

getting good results locally:
```
snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
                              balance_before              balance_after               balance_delta
symbol                                                                                             
BADGER            109,850.267274299902285728  59,850.267274299902285728  -50,000.000000000000000000
WBTC                    0.018018000000000000       0.152614980000000000        0.134596980000000000
BADGERWBTC-f          243.447151239322582783     919.168852236386138053      675.721700997063555270
bibbtc/sbtcCRV-f       10.298982302770983127       1.167289358155794127       -9.131692944615189000
ibbtc/sbtcCRV-f         0.146913552955539075       0.000000000000000000       -0.146913552955539075
```

only thing is that right now if wbtc balance would be considerable, it doesnt subtract this from `wbtc_amount` when withdrawing. could you add that? especially seen that soon we will have the 2+ wbtc coming in from the univ3 fees. waiting for that then first will mean we dont have to withdraw more wbtc than needed.

**Comment by jalbrekt85** [comment]
> indeed already done before in #34
> 
> getting good results locally:
> 
> ```
> snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
>                               balance_before              balance_after               balance_delta
> symbol                                                                                             
> BADGER            109,850.267274299902285728  59,850.267274299902285728  -50,000.000000000000000000
> WBTC                    0.018018000000000000       0.152614980000000000        0.134596980000000000
> BADGERWBTC-f          243.447151239322582783     919.168852236386138053      675.721700997063555270
> bibbtc/sbtcCRV-f       10.298982302770983127       1.167289358155794127       -9.131692944615189000
> ibbtc/sbtcCRV-f         0.146913552955539075       0.000000000000000000       -0.146913552955539075
> ```
> 
> only thing is that right now if wbtc balance would be considerable, it doesnt subtract this from `wbtc_amount` when withdrawing. could you add that? especially seen that soon we will have the 2+ wbtc coming in from the univ3 fees. waiting for that then first will mean we dont have to withdraw more wbtc than needed.

good idea

**Review by jorijnsmit — APPROVED** [review]
nice.

again i suggest to post this after the wbtc univ3 fees have been received from the vault, this to minimise the amount of bibbtc we withdraw.

**Review by petrovska-petro — APPROVED** [review]
Works well andwd from dog food necessarily wbtc amount (leaving idle ~ 0.13 wbtc) ✅ 

```
snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
                              balance_before              balance_after               balance_delta
symbol                                                                                             
BADGER            109,850.267274299902285728  59,850.267274299902285728  -50,000.000000000000000000
WBTC                    0.018018000000000000       0.153649970000000000        0.135631970000000000
BADGERWBTC-f          243.447151239322582783     916.072852985458597581      672.625701746136014798
bibbtc/sbtcCRV-f       10.298982302770983127       1.268508115855211127       -9.030474186915772000
ibbtc/sbtcCRV-f         0.165220608025252497       0.000000000000000000       -0.165220608025252497 
```

**Pull request merged**
