### PR TITLE
feat: remove graviAura's keeper

### PR DESCRIPTION
**Pull request by sajanrajdev**
Tackles #1321

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
note: merging main to prevent calling old gnosis safe api endpoints

**Review by gosuto-inzasheru — APPROVED** [review]
does what it says on the box:

prevents calling `earn` on graviaura via keeper access control. still remains callable by gov

**Review by petrovska-petro — APPROVED** [review]
Sets to null addr the keeper on gravi, blocking the action ✅

**Comment by sajanrajdev** [comment]
> does what it says on the box:
> 
> prevents calling `earn` on graviaura via keeper access control. still remains callable by gov

Correct, it is ok for actions to be callable from Multis for this purpose. The fear here is that a earn is triggered accidentally by a misconfiguration on the bot. This action removes that issue.

**Pull request merged**
