### PR TITLE
chore: simulate pool creation and initial deposit

### PR DESCRIPTION
**Pull request by btcookies**

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
moving my comments from discord here for visibility
> try from trops
[8:07 PM]
and get the aura from withdrawing some from the graviaura there
[8:08 PM]
also it is now calling an unnecessary approve on the bpt
[8:08 PM]
due to the approve loop in the balancer class
[8:08 PM]
maybe exclude the token from that loop if token==pool

**Comment by gosuto-inzasheru** [comment]
init joinpool was made by @hasherror: https://etherscan.io/tx/0xeb3dc49452ae6d948db46618aeebf612720e19a49ab7ef63dfcd654db31f99ec
pool/token: `0x6A9603E481Fb8F2c09804ea9AdaB49A338855B90`
gauge deployment: https://etherscan.io/tx/0x8eafd97d79db2d47d22a3dadb33f42b6cc0cebb99670730343ef1db362ccd48e#eventlog

**Comment by gosuto-inzasheru** [comment]
i do think the balancer code part of this pr is still something we should merge though, good to have for next time!

**Review by gosuto-inzasheru — DISMISSED** [review]
lgtm

**Review by jalbrekt85 — APPROVED** [review]

**Review by gosuto-inzasheru — APPROVED** [review]

**Pull request merged**
