### PR TITLE
VestedCVX upgrade Script to include BribesProcessor

### PR DESCRIPTION
**Pull request by sajanrajdev**
This PR tackles issue #406 

Run queue with:
```
brownie run scripts/issue/406/upgrade_vestedcvx_strat.py
```
Run execution with:
```
brownie run scripts/issue/406/upgrade_vestedcvx_strat.py main false
```
Run simulation with:
```
brownie run scripts/issue/406/upgrade_vestedcvx_strat.py main false true
```

### CODE REVIEW

**Comment by sajanrajdev** [comment]
Simulation running successfully:
```
Running 'scripts/issue/406/upgrade_vestedcvx_strat.py::main'...
Simulating upgrade...
Transaction sent: 0x607affd63b9c11fc8a86a964346ee031d4c9643b47e9b93f1387d588694702e2
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 1
  IProxyAdmin.upgrade confirmed   Block: 14667624   Gas used: 32625 (0.27%)

Simulation Successful!
Transaction sent: 0x420521ad34b78dabb6d5c377ffa4ad30cef8005161880327e81756ff6c26f8c0
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 68
  Gnosis Safe.approveHash confirmed   Block: 14667624   Gas used: 46206 (0.39%)

Transaction sent: 0x509fac7c6c6b123577e826cba16ca96fb4dbddfab84d1c6dfe4ffc9da290b657
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 180
  Gnosis Safe.approveHash confirmed   Block: 14667625   Gas used: 46206 (0.39%)

Transaction sent: 0x9fe4de1cd88ae10a925c5b58cdd2a7a631498b89cfe86a9873eeba37adb1ade1
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 0
  Gnosis Safe.approveHash confirmed   Block: 14667626   Gas used: 46206 (0.39%)

Transaction sent: 0xb276b4729e76730bc87e21ff20ecfb2c85e1f17c664c294b05af3888951aa509
  Gas price: 0.0 gwei   Gas limit: 77640   Nonce: 69
  Gnosis Safe.execTransaction confirmed   Block: 14667627   Gas used: 29012 (37.37%)
  ```

**Comment by GalloDaSballo** [comment]
WARNING!

I must renounce ownership and set `manager` to a Multisig before this upgrade can go live

In Verifying the code, also verify that the `manager` is a known multi-sig!!!

**Comment by sajanrajdev** [comment]
Added check to ensure that the BribesProcessor's manager points to TechOps before upgrade execution

**Review by petrovska-petro — COMMENTED** [review]
confirming:

- processor version with dev_msig rights to update pricer. [ref](https://etherscan.io/address/0xbed8f323456578981952e33bbfbe80d23289246b#code#F4#L131)

- latest processor deployed pointing. [ref](https://etherscan.io/address/0x57961a757bA249E616c1940548401b7CdF83a849#code#F1#L68)

- in multi bribe claims, usage of `nonZeroDiff` bool. [ref-1](https://etherscan.io/address/0x57961a757bA249E616c1940548401b7CdF83a849#code#F1#L264) & [ref-2](https://etherscan.io/address/0x57961a757bA249E616c1940548401b7CdF83a849#code#F1#L351) as long as one diff is > 0, processor will be notify and update *lastBribeAction*


Waiting on manager update for final approval

**Comment by GalloDaSballo** [comment]
Delegated to TechOps
https://etherscan.io/tx/0x02f2448d2e8640b3738b9f36e1266142e514ad12749fdd56a8e71936daec4f00

**Review by petrovska-petro — APPROVED** [review]
Manager granted to *techops*, rest looks good ✅

**Review by jorijnsmit — APPROVED** [review]
confirmed addresses, good to go!

**Review by shuklaayush — APPROVED** [review]
LGTM

**Pull request merged**
