### PR TITLE
script: for loop treasury council members and add them as owner

### PR DESCRIPTION
**Pull request by jorijnsmit**
script to solve #442

### CODE REVIEW

**Review by petrovska-petro — APPROVED** [review]
Script looks good and changes threshold to 5

Confirming at my end is the right address for my signer

would be great to get same confirmation for all the addr additions on this PR as there is no other way to confirm address veracity

**Comment by dapp-whisperer** [comment]
confirmed dapp address

**Review by sajanrajdev — APPROVED** [review]
Iterates through list of signers' addresses and adds them to the multisig if not already added. Also, sets the threshold to 5. 

LGTM

Also, confimed Saj's address.

**Review by Hal69k — COMMENTED** [review]
Confirming 1500 address is correct

**Comment by shuklaayush** [comment]
Confirming ayush's address

**Comment by MrrPo** [comment]
Confirming Po's address is correct

**Pull request merged**
