### PR TITLE
updated thresher for q3

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
will still leave the pr in draft for now, but maybe some eyes on it could help

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
ready for review, leaving the swap from fPmBTCHBTC and imBTC to wbtc for next time

**Comment by gosuto-inzasheru** [comment]
getting `GS013` revert with preview on btw, it didnt have this before

**Review by petrovska-petro — APPROVED** [review]
- scripts modifications looks good. i also get GS013 locally without skipping preview

- will advise to run this after we claim `bal` from old tcl position in trops (~4.8k bal claimable)

- will consolidate a total of 25k bcvxcrv after successful tx, can be used to handle a bit of the deficit on the tree (at the moment ~68k-70k)

- similarly it sends enough bvecvx into voter, which can be used to cover fully the bvecvx deficit

**Comment by gosuto-inzasheru** [comment]
i thought we had claimed that already! i actually removed the code to claim. i added it back :)

**Review by petrovska-petro — APPROVED** [review]

**Review by jalbrekt85 — APPROVED** [review]
thresher is ready for farming

**Pull request merged**
