### PR TITLE
Script to Upgrade BadgerSettPeak and Sweep bveCVX

### PR DESCRIPTION
**Pull request by sajanrajdev**
This PR closes issue #204 

Upgrades the logic of ibBTC's BadgerSettPeak to add a sweep function for unprotected tokens. Sweeps the stuck bveCVX into the Treasury Vault multi.

Use the following to run:
```
brownie run scripts/issue/204/upgrade_peak_and_sweep.py
```

### CODE REVIEW

**Comment by GalloDaSballo** [comment]
Screenshot 2022-03-25 at 18 04 12


LGTM Upgrade will change to new impl

New impl is the one from [latest update](https://github.com/Badger-Finance/ibbtc/pull/1)

**Review by GalloDaSballo — DISMISSED** [review]
LGTM see above

**Review by jorijnsmit — CHANGES_REQUESTED** [review]
looks good, except for i would replace `TREASURY_VAULT` with the new voter msig: `0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b`
(see #282, #302)

**Comment by petrovska-petro** [comment]
> 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b

+1, to save another tx from vault to `bvecvx_voting_multisig`

**Review by jorijnsmit — APPROVED** [review]

**Review by petrovska-petro — APPROVED** [review]
changed destination to `bvecvx_voting_multisig` ✅

**Pull request merged**
