### PR TITLE
refactor tests

### PR DESCRIPTION
**Pull request by jalbrekt85**
solves #389 and organizes protocol specific fixtures

### CODE REVIEW

**Review by jorijnsmit — COMMENTED** [review]
had to move dai and cvxcrv fixtures to the general conftest since they are used across multiple platform tests.

also still getting quite a few fails/errors when running `brownie test`, but maybe we can fix that in a separate issue?

**Comment by jalbrekt85** [comment]
> had to move dai and cvxcrv fixtures to the general conftest since they are used across multiple platform tests.
> 
> also still getting quite a few fails/errors when running `brownie test`, but maybe we can fix that in a separate issue?

fixtures have been moved. getting rest of tests to pass involving protocols like balancer or curve will require a decent amount of changes to great ape safe classes so i'd say it is better to handle in another ticket

**Review by jorijnsmit — APPROVED** [review]
i created #568 so we dont forget

**Review by petrovska-petro — APPROVED** [review]
conftest refactoring per protocol looks fine, just bunch of test are E or F. in light of #568 approving.

test ref from local run:

Screenshot 2022-06-22 at 15 05 37

**Pull request merged**
