### PR TITLE
fix: pass correct dtype for choice and drop metadata if empty

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
we found some tiny bugs when testing in prod, which of course for a hash always matter. dtype for the weighted choice has to be `dict` and for the single choice has to be `int`.

was successfully able to reproduce the sigs produced by posting the same vote through the ui:
```
>>> voter.init_snapshot('0x632726577e9c186a8827311b8702dcfd98f26376237b9715e64eafa61d6d7672')
>>> voter.snapshot.create_payload_hash(timestamp=1660916596, choice={'80/20 BADGER/WBTC': 1})
msg hash: 0x4f7a4ac87a416dfe0b64b26613bedbdda8bb408da76bc2da4274d1ef8a34e1e8
```
and
```
>>> voter.init_snapshot('0x89b36c1571aa9d55e2c692a3524ec80ce4ef9668b3cb796da42e13c5b3462235')
>>> voter.snapshot.create_payload_hash(timestamp=1660923084, choice='Yes')
msg hash: 0xf393f8ace6ff7dcaab84e11d1bb7a577d5f6e797bdc5f275e653a6eb4c5a55a7
```

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
hold up needs some adjusting in `vote_and_post` as well i realise now

**Comment by gosuto-inzasheru** [comment]
ok ready

**Review by jalbrekt85 — APPROVED** [review]
weighted choices are sent to payload as `dict` and `int` for single choices ✅ lgtm

**Review by petrovska-petro — APPROVED** [review]
msh hashes matches with the right hash tried with weighted and single choice proposal type compare what was produced via gnosis ui ✅ 

nice touch moving `metadata` to None as default 👍

**Pull request merged**
