### PR TITLE
topups from vault for week 9

### PR DESCRIPTION
**Pull request by jorijnsmit**
solves #191, #196, #197, #198

### CODE REVIEW

**Review by petrovska-petro — DISMISSED** [review]
LGTM!

**Review by sajanrajdev — DISMISSED** [review]
Handles BADGER for Arb bridging, BADGER and DIGG top-ups to the tree and USDC/EUR redirection to trops.

**Comment by jorijnsmit** [comment]
also solves #205

**Review by sajanrajdev — APPROVED** [review]
Supplies the missing amount of wBTC for TCL to trops in the form of bibbtc-sbtc-f (Confirmed that there is enough in the vault for this).

**Review by petrovska-petro — APPROVED** [review]
Adds the `bcrvIbBTC`transfer for univ3 lowest range coverage to be handled in treasury ops ✅

**Pull request merged**
