### PR TITLE
feat: register fantom vaults

### PR DESCRIPTION
**Pull request by axejintao**
# Summary

Registers Fantom vaults on the v2 registry with the proper parameters

## Issues

#365 partial implementation

### Test Run

```
Running 'scripts/issue/365/register_vaults.py::register_vaults'...
['0xFce6e3115D84c94df98BD286C1C67279dc021361', 'v1', 'name=%F0%9F%91%BB%20BOO/xBOO,protocol=Solidex,behavior=Ecosystem', 0]
Transaction sent: 0x0d6f70d397978871c91df42226c716978a69163493593d9e6c7d0cb4f6f37058
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 1
  Transaction confirmed   Block: 39186948   Gas used: 228439 (1.90%)

Promote: 0xFce6e3115D84c94df98BD286C1C67279dc021361 (v1) to 0
['0xB6D63A4e5Ca740e96C26AdAbcAc73BE78Ee39Dc5', 'v1', 'name=WBTC/renBTC,protocol=Solidex,behavior=Compounder', 2]
Transaction sent: 0xeff17c028a18702e5dce7a70646fc35ef8e25ee322177811bad3b893dbb9c604
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
  Transaction confirmed   Block: 39186949   Gas used: 248343 (2.07%)

Promote: 0xB6D63A4e5Ca740e96C26AdAbcAc73BE78Ee39Dc5 (v1) to 2
['0x7cc6049a125388B51c530e51727A87aE101f6417', 'v1', 'name=WFTM/SEX,protocol=Solidex,behavior=Ecosystem Helper', 0]
Transaction sent: 0x2f66e2224bc0c7eff72530326cc05897ee52c8a24f725e830d289c7657f99c37
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 3
  Transaction confirmed   Block: 39186950   Gas used: 210098 (1.75%)

Promote: 0x7cc6049a125388B51c530e51727A87aE101f6417 (v1) to 0
['0xC7cBF5a24caBA375C09cc824481F5508c644dF28', 'v1', 'name=SOLID/SOLIDsex,protocol=Solidex,behavior=Ecosystem Helper', 0]
Transaction sent: 0x256948a50cff11042c4dfcab81643657636c636ffc58b11e713727a9c499c524
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 4
  Transaction confirmed   Block: 39186951   Gas used: 211472 (1.76%)

Promote: 0xC7cBF5a24caBA375C09cc824481F5508c644dF28 (v1) to 0
['0xd9770deC6fdA576450e66f0c441B6b8755F7184A', 'v1', 'name=WEVE/USDC,protocol=Solidex,behavior=Compounder', 2]
Transaction sent: 0x67d116bf6fc1ade041d20a9d2f3654c82a404b0319f0303e84822e2b8e1fcc95
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 5
  Transaction confirmed   Block: 39186952   Gas used: 232885 (1.94%)

Promote: 0xd9770deC6fdA576450e66f0c441B6b8755F7184A (v1) to 2
['0x4145a9B8B7bdC76F14e65c26f9c71e23B9069b25', 'v1', 'name=WFTM/CRV,protocol=Solidex,behavior=DCA', 2]
Transaction sent: 0xb174dade4252ab3aaf0ed3548cec75f75116e2210aca531599022032530af987
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 6
  Transaction confirmed   Block: 39186953   Gas used: 232572 (1.94%)

Promote: 0x4145a9B8B7bdC76F14e65c26f9c71e23B9069b25 (v1) to 2
['0x1AaF7f8154704D80E2380B3DbC967FD0486016e0', 'v1', 'name=USDC/MIM,protocol=Solidex,behavior=DCA', 2]
Transaction sent: 0x2d77890c613c508bb9c84940ab4456f492d4f9e8f1dccb4ec9621344250cb02c
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 7
  Transaction confirmed   Block: 39186954   Gas used: 232572 (1.94%)

Promote: 0x1AaF7f8154704D80E2380B3DbC967FD0486016e0 (v1) to 2
['0x9a28eeFB2c5F8311f37c39314D78Be85C54B5da6', 'v1', 'name=WFTM/renBTC,protocol=Solidex,behavior=DCA', 2]
Transaction sent: 0xe34139b10348097dc89778ff9c8cbbbe3e4634452d4c6938b8f7e3366c78e425
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 8
  Transaction confirmed   Block: 39186955   Gas used: 233259 (1.94%)

Promote: 0x9a28eeFB2c5F8311f37c39314D78Be85C54B5da6 (v1) to 2
['0x02330E37fcc7C27eB4632b3E31b951fDE5126c48', 'v1', 'name=GEIST/g3CRV,protocol=Solidex,behavior=DCA', 0]
Transaction sent: 0x5bf67d1716c230eed64b19b3bd4cd335e0751fc72f134a819655bb081ee0c2ce
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 9
  Transaction confirmed   Block: 39186956   Gas used: 210629 (1.76%)

Promote: 0x02330E37fcc7C27eB4632b3E31b951fDE5126c48 (v1) to 0
['0x60c5A975Bd0511e45D4C9Ae5592c8CA412BE2310', 'v1', 'name=%F0%9F%91%BB%20WFTM/CRV,protocol=Solidex,behavior=Ecosystem', 0]
Transaction sent: 0xfa16661ae36ffdd075037579635c6f75562fb38916292d6969af8f5885f124a2
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 10
  Transaction confirmed   Block: 39186957   Gas used: 213439 (1.78%)

Promote: 0x60c5A975Bd0511e45D4C9Ae5592c8CA412BE2310 (v1) to 0
['0x561f4dBaFA71ad05694C7ea1b894b9D99f684281', 'v1', 'name=%F0%9F%91%BB%20USDC/MIM,protocol=Solidex,behavior=Ecosystem', 0]
Transaction sent: 0x2acfc2efaaadb905b7dda0d09ea30d1ed47b60a2df5e4fc698b612e3eb1f9ec7
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 11
  Transaction confirmed   Block: 39186958   Gas used: 213439 (1.78%)

Promote: 0x561f4dBaFA71ad05694C7ea1b894b9D99f684281 (v1) to 0
['0x77e803F7d0B6d85731F68CfE1f1CA4c48de105F4', 'v1', 'name=%F0%9F%91%BB%20WFTM/SCREAM,protocol=Solidex,behavior=Ecosystem', 0]
Transaction sent: 0x8cbdf39759e6906f84bcd53fddff437d56aca0951d78cb7a6eea6b5df46a3738
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 12
  Transaction confirmed   Block: 39186959   Gas used: 234672 (1.96%)

Promote: 0x77e803F7d0B6d85731F68CfE1f1CA4c48de105F4 (v1) to 0
['0x609A51e13fd0896c0c02f0B642756533b29f36Ab', 'v1', 'name=%F0%9F%91%BB%20WFTM/renBTC,protocol=Solidex,behavior=Ecosystem', 0]
Transaction sent: 0xd04dbcfecd1284701b0aff82ed82c116124cd232063907983fb0ba8295d1697e
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 13
  Transaction confirmed   Block: 39186960   Gas used: 234672 (1.96%)

Promote: 0x609A51e13fd0896c0c02f0B642756533b29f36Ab (v1) to 0
['0x3f96f8cA67AcDE9041AD62125C5a4D062b07872c', 'v1', 'name=%F0%9F%91%BB%20WFTM/TOMB,protocol=Solidex,behavior=Ecosystem', 0]
Transaction sent: 0x26e191dd3693e4530d8215e058db4591a44ae1f3cbb86e4c3b034ce0772b9bc2
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 14
  Transaction confirmed   Block: 39186961   Gas used: 234214 (1.95%)

Promote: 0x3f96f8cA67AcDE9041AD62125C5a4D062b07872c (v1) to 0
['0x96d4dBdc91Bef716eb407e415c9987a9fAfb8906', 'v1.5', 'name=bveOXD,protocol=0xDAO,behavior=None', 2]
Transaction sent: 0xbc52fd740e2e4b4e0923786917f133392780369069e243224948010b05dff4ba
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 15
  Transaction confirmed   Block: 39186962   Gas used: 246692 (2.06%)

Promote: 0x96d4dBdc91Bef716eb407e415c9987a9fAfb8906 (v1.5) to 2
['0xa8bD8655A0dCABE76913D821Ab437562276b3B59', 'v1.5', 'name=boxSOLID,protocol=0xDAO,behavior=Ecosystem Helper', 2]
Transaction sent: 0x36008a5cb5174bf71635463dec6b7ee9cc08de6cf4cdfed85420d8aa8c20d691
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 16
  Transaction confirmed   Block: 39186963   Gas used: 232294 (1.94%)

Promote: 0xa8bD8655A0dCABE76913D821Ab437562276b3B59 (v1.5) to 2
['0xbF2F3a9ba42A00CA5B18842D8eB1954120e4a2A9', 'v1.5', 'name=bveOXD/OXD,protocol=0xDAO,behavior=Ecosystem Helper', 2]
Transaction sent: 0xdaeff9676104b92615d1f09ba869ad43bfec27841b05af8ae3a2de2231830194
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 17
  Transaction confirmed   Block: 39186964   Gas used: 232740 (1.94%)

Promote: 0xbF2F3a9ba42A00CA5B18842D8eB1954120e4a2A9 (v1.5) to 2
['0xcd1e62b390373fcFeA87Dd06E2497Fdc907935fA', 'v1.5', 'name=USDC/DEI,protocol=0xDAO,behavior=Ecosystem', 2]
Transaction sent: 0x5699605d460b610b629a1a09465f3805e58c9d65d2b2e1c6b847c2cef0721567
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 18
  Transaction confirmed   Block: 39186965   Gas used: 232210 (1.94%)

Promote: 0xcd1e62b390373fcFeA87Dd06E2497Fdc907935fA (v1.5) to 2
Transaction sent: 0xab05cb3e7f027cf9ecd231b1dd7a09c9ec4f9cd841001565c07bb0ab956103d0
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 0
  Gnosis Safe.approveHash confirmed   Block: 39186948   Gas used: 46184 (0.38%)

Transaction sent: 0x6e8875d7da0b3a95dd24ef640b33315b26724265d265a8297ba48eb57b7b4bfd
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 0
  Gnosis Safe.approveHash confirmed   Block: 39186949   Gas used: 46184 (0.38%)

Transaction sent: 0x913041bccf2a5dc7bdb6db479a22de112dea28afdbec25a408f350ea95fb9e6d
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 9
  Gnosis Safe.approveHash confirmed   Block: 39186950   Gas used: 46184 (0.38%)
  ```

### CODE REVIEW

**Review by sajanrajdev — COMMENTED** [review]
I would recommend that we set all the guarded vaults (2) to prodcution (3) and take this opportunity to remove the caps and unguard.

**Comment by jorijnsmit** [comment]
note: depends on #493 being merged for the `promote_vault` method

**Review by sajanrajdev — APPROVED** [review]
Addresses, versions and MetaData - LGTM

Note: Live vaults will be set with state `3` (Production/Open) instead of their current guarded state. This means that vaults deposit caps should be removed along with this change - Will coordinate with @shuklaayush to do these as we hold ownership of the guestlists.

**Review by jorijnsmit — COMMENTED** [review]
lgtm, except for some vault addresses which are not on the website which i could therefor not verify.

**Comment by sajanrajdev** [comment]
> lgtm, except for some vault addresses which are not on the website which i could therefor not verify.

You can verify deprecated vaults here: https://deprecated-vaults.netlify.app/

**Review by jorijnsmit — APPROVED** [review]

**Pull request merged**
