### PR TITLE
feat: include bunni tcl strat script

### PR DESCRIPTION
**Pull request by petrovska-petro**
Tackles #1216 

```
brownie run scripts/badger/bunni_tcl_strategy
```

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
getting an assertion error on `bunny.py#L249`, or if commented out `IOptionsToken.exercise` reverts on a `typed error: 0xd193bd20`.

**Comment by jalbrekt85** [comment]
> getting an assertion error on `bunny.py#L249`, or if commented out `IOptionsToken.exercise` reverts on a `typed error: 0xd193bd20`.

is due to an oversight on slippage control. tests were with small claims so the `math.ceil` was enough to pass. updated to use a wider slipp calc so to account for our large claims: 9801892

**Comment by gosuto-inzasheru** [comment]
@jalbrekt85 why comment out the assert though?

**Review by gosuto-inzasheru — APPROVED** [review]
runs successful now.

harvests bunni and converts to weth!

**Pull request merged**
