### PR TITLE
chore: minor bugs and optimisations

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
bit random stuff, all related to aura ecosystem interactions

### CODE REVIEW

**Review by jalbrekt85 — DISMISSED** [review]

**Review by sajanrajdev — APPROVED** [review]
- Adds try/catch to Snapshot voting library's formatting function
- Adds missing bribe tokens from list
- Adds tokens to snap on Aura TCL harvest script 

LGTM

**Comment by gosuto-inzasheru** [comment]
sorry guys need stamp again, had to fix a merge conflict.

**Review by sajanrajdev — APPROVED** [review]

**Review by jalbrekt85 — DISMISSED** [review]

**Comment by jalbrekt85** [comment]
looks like there is still a merge conflict

**Comment by gosuto-inzasheru** [comment]
crap that was introduced by merging another pr. lets try again.

**Review by sajanrajdev — APPROVED** [review]

**Pull request merged**
