### PR TITLE
Emissions schedule for BIP-88 bribe payout (Q2-2022)

### PR DESCRIPTION
**Pull request by Tritium-VLK**
For #316

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
Runlog on eth:
`
Total emissions during 31-03-22 : badger=19143.0, digg=2.89480223093290494584945128492933302915533E+74 and bcvxCrv=0
Transaction sent: 0x187874a0de84a6c5e23a8207e4bac45af074e9604bf241ea9152133afad07111
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 28
  Gnosis Safe.approveHash confirmed   Block: 14483915   Gas used: 46206 (0.39%)

Transaction sent: 0xaef8c10a3339d16769d716c0299bb2e1d2b074b6a7da69060587013d2eaa000f
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 13
  Gnosis Safe.approveHash confirmed   Block: 14483916   Gas used: 46206 (0.39%)

Transaction sent: 0x1dd67792d6726c14fbceda576920d2d97771d27ef7d262a220dc605d9b85063c
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 234
  Gnosis Safe.approveHash confirmed   Block: 14483917   Gas used: 46206 (0.39%)

Transaction sent: 0xa85dd05cebc90f80e79b9e7298b1ed3ce626f537aadd799787b30638b4ef0e31
  Gas price: 0.0 gwei   Gas limit: 502107   Nonce: 29
  Gnosis Safe.execTransaction confirmed   Block: 14483918   Gas used: 445439 (88.71%)

Transaction was Mined 
---------------------
Tx Hash: 0xa85dd05cebc90f80e79b9e7298b1ed3ce626f537aadd799787b30638b4ef0e31
From: 0x10C7a2ca16116E5C998Bfa3BC9CEF464475B18ff
To: 0x86cbD0ce0c087b482782c181dA8d191De18C8275
Value: 0
Function: Gnosis Safe.execTransaction
Block: 14483918
Gas Used: 445439 / 502107 (88.7%)

Events In This Transaction
--------------------------
├── AdminUpgradeabilityProxy (0x0A4F4e92C3334821EbB523324D09E321a6B0d8ec)
│   ├── UnlockScheduleSet
│   │   ├── beneficiary: 0xaE96fF08771a109dc6650a1BdCa62F2d558E40af
│   │   ├── token: 0x3472A5A71965499acd81997a54BBA8D852C6E53d
│   │   ├── totalAmount: 17591000000000000000000
│   │   ├── start: 1648684800
│   │   ├── end: 1649289600
│   │   ├── duration: 604800
│   │   ├── timestamp: 14483918
│   │   └── blockNumber: 1648594223
│   ├── UnlockScheduleSet
│   │   ├── beneficiary: 0x2B5455aac8d64C14786c3a29858E43b5945819C0
│   │   ├── token: 0x3472A5A71965499acd81997a54BBA8D852C6E53d
│   │   ├── totalAmount: 1552000000000000000000
│   │   ├── start: 1648684800
│   │   ├── end: 1649289600
│   │   ├── duration: 604800
│   │   ├── timestamp: 14483918
│   │   └── blockNumber: 1648594223
│   └── UnlockScheduleSet
│       ├── beneficiary: 0x88128580ACdD9c04Ce47AFcE196875747bF2A9f6
│       ├── token: 0x798D1bE841a82a273720CE31c822C61a67a601C3
│       ├── totalAmount: 289480223093290494584945128492933302915532807943461169556905186705255956480
│       ├── start: 1648684800
│       ├── end: 1649289600
│       ├── duration: 604800
│       ├── timestamp: 14483918
│       └── blockNumber: 1648594223
│   
└── Gnosis Safe (0x86cbD0ce0c087b482782c181dA8d191De18C8275)
    └── ExecutionSuccess
        ├── txHash: 0xf4d88aee9c95bab74933834754613c919d21589d74dd85274f760d96573e878f
        └── payment: 0

{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x120b4ba60>,
│   'safe_address': '0x86cbD0ce0c087b482782c181dA8d191De18C8275',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000034b000a4f4e92c3334821ebb523324d09e321a6b0d8ec000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4768f304f000000000000000000000000ae96ff08771a109dc6650a1bdca62f2d558e40af0000000000000000000000003472a5a71965499acd81997a54bba8d852c6e53d0000000000000000000000000000000000000000000003b99c2a52e3387c0000000000000000000000000000000000000000000000000000000000006244ef0000000000000000000000000000000000000000000000000000000000624e29800000000000000000000000000000000000000000000000000000000000093a80000a4f4e92c3334821ebb523324d09e321a6b0d8ec000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4768f304f0000000000000000000000002b5455aac8d64c14786c3a29858e43b5945819c00000000000000000000000003472a5a71965499acd81997a54bba8d852c6e53d0000000000000000000000000000000000000000000000542253a126ce400000000000000000000000000000000000000000000000000000000000006244ef0000000000000000000000000000000000000000000000000000000000624e29800000000000000000000000000000000000000000000000000000000000093a80000a4f4e92c3334821ebb523324d09e321a6b0d8ec000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4768f304f00000000000000000000000088128580acdd9c04ce47afce196875747bf2a9f6000000000000000000000000798d1be841a82a273720ce31c822c61a67a601c300a3d70a3d70a3d8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006244ef0000000000000000000000000000000000000000000000000000000000624e29800000000000000000000000000000000000000000000000000000000000093a80000000000000000000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 714513,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 239,
│   '_safe_version': '1.1.1',
│   '_chain_id': None
}
`

**Review by mitche50 — COMMENTED** [review]
BIP_88_Emissions.csv is an empty file, can you please upload the correct one?

**Review by jorijnsmit — COMMENTED** [review]
this was executed, see https://github.com/Badger-Finance/badger-multisig/issues/316

still having the csv would be nice @Tritium-VLK

**Comment by petrovska-petro** [comment]
reminder to push the csv and json formatted*

**Review by petrovska-petro — APPROVED** [review]

**Review by jorijnsmit — APPROVED** [review]

**Comment by petrovska-petro** [comment]
signing commit issues, will create another fresh pr with same content, closing this for now

**Pull request closed without merging**
