### PR TITLE
Migrate wd fee to trops in byvWBTC sett

### PR DESCRIPTION
**Pull request by petrovska-petro**
Tackles #540 

Commands to be run in order, setting from dev_msig and the acceptance from the new recipient for the wd fee:

```
brownie run issue/540/migrate_wd_fee set_affiliate

brownie run issue/540/migrate_wd_fee accept_affiliate
```

### CODE REVIEW

**Comment by sajanrajdev** [comment]
I would defer the last approval to @dapp-whisperer. For the Yearn wrapper, the `Affiliate` is basically the "governance" equivalent from our vaults. In this case, the affiliate has the power to change the guardian, manager, withdrawal fees. Imo, this last one is the only parameter that could be dangerous should the affiliate be compromised as WD are capped up to MAX_BPS (100%).

Other than this concern, I don't see a big issue.

**Review by Tritium-VLK — APPROVED** [review]

**Comment by dapp-whisperer** [comment]
I agree with Saj take, we should create a new variable for the treasury, which receives all fees. Changing the affiliate is akin to setting governance to the treasury. We want a separation between contract governance and the treasury

**Comment by sajanrajdev** [comment]
@petrovska-petro, `byvWBTC` proxy's is owned by the devProxyAdmin, upgrade should go through the Timelock:
image

Unfortunately, the dev of this wrapper was done on [badger-system](https://github.com/Badger-Finance/badger-system/blob/master/contracts/yearn/SimpleWrapperGatedUpgradeable.sol)... it would probably be an overkill to extract it to make this change so we should probably handle it there as we did with Digg.

**Comment by dapp-whisperer** [comment]
So my thought on this is:
- modify the contract, adding a `treasury` var that receives fees. This variable can be set by `affiliate`
- run the upgrade to this new logic, and add treasury vault to receive fees

**Comment by petrovska-petro** [comment]
> @petrovska-petro i guess this can be closed now..?

closing 🔐

**Pull request closed without merging**
