### PR TITLE
Digg upgrade script

### PR DESCRIPTION
**Pull request by sajanrajdev**
Closes Issue #520 

Upgrades Digg to new logic with oneTimeMint, Sweep and Toggle Rebase

Run queue with:
```
brownie run scripts/issue/520/upgrade_digg.py
```
Run execution with:
```
brownie run scripts/issue/520/upgrade_digg.py main false
```
Run simulation with:
```
brownie run scripts/issue/520/upgrade_digg.py main false true
```

### CODE REVIEW

**Review by mitche50 — APPROVED** [review]

**Comment by shuklaayush** [comment]
I think we should also disable rebasing in the same script using `toggleRebase`

**Comment by jorijnsmit** [comment]
> The error comes from it trying to call `oneTimeMint` from Digg with the old logic. Not sure why Brownie does that but the simulation checks confirms that the function will be callable after upgrade.

i think this occurs because in running the preview, it can only gather the receipts for the msig txs. the `proxyAdmin.upgrade(digg.address, NEW_LOGIC, {'from': timelock})` thus doesnt get taken into account after preview resets the chain.

locally i isolated the upgrade logic into a different function, and then the preview for the one time mint does run successfully.

**Review by jorijnsmit — COMMENTED** [review]
thorough upgrade script saj!

good to go imo except for ayush's comment on explicitly disabling rebasing as well.

**Review by mitche50 — APPROVED** [review]
LGTM - Saj showed tx trace from simulation which shows `Rebase paused` revert as expected as you cannot use `with brownie.reverts()` on scripts

**Review by jorijnsmit — APPROVED** [review]
lessgooo

**Review by mitche50 — APPROVED** [review]

**Pull request merged**
